######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 26 19:36:43 2013
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../Calculator.h ../Errors.h
SOURCES += TestHof.cpp ../Calculator.cpp
